/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EarthCafe;
import MainMenu.MainMenu;
import java.awt.TextField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author shanjutha
 */
public class EarthCafe extends javax.swing.JFrame {

    /**
     * Creates new form EarthCafe
     */
    public EarthCafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        dineIn = new javax.swing.JButton();
        toGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 1200, 850));
        setMinimumSize(new java.awt.Dimension(1200, 850));
        setPreferredSize(new java.awt.Dimension(1200, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon("/Users/shanjutha/NetBeansProjects/EarthCafeRestaurant/images/4e2a4a22-67ad-4826-b9a0-8e36eda39090_200x200.png")); // NOI18N
        logo.setToolTipText("");
        logo.setName(""); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 190));

        welcome.setFont(new java.awt.Font("Digory Doodles", 0, 50)); // NOI18N
        welcome.setText("welcome to Earth Cafe!");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        dineIn.setFont(new java.awt.Font("Century Gothic", 1, 75)); // NOI18N
        dineIn.setText("DINE-IN");
        dineIn.setToolTipText("");
        dineIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineInActionPerformed(evt);
            }
        });
        getContentPane().add(dineIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 490, 130));

        toGo.setFont(new java.awt.Font("Century Gothic", 1, 75)); // NOI18N
        toGo.setText("TO-GO");
        toGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGoActionPerformed(evt);
            }
        });
        getContentPane().add(toGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 490, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineInActionPerformed
        MainMenu Menu = new MainMenu();
        Menu.setVisible(true);
        String Type = "Dine-In";
        this.setVisible(false);
    }//GEN-LAST:event_dineInActionPerformed

    private void toGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGoActionPerformed
        MainMenu Menu = new MainMenu();
        Menu.setVisible(true);
        String Type = "To-Go";
        this.setVisible(false);
    }//GEN-LAST:event_toGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EarthCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EarthCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EarthCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EarthCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EarthCafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dineIn;
    private javax.swing.JLabel logo;
    private javax.swing.JButton toGo;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
